/**
 * Auto Post Scheduler
 *
 * Automatically generates AI posts and schedules them for Threads publishing.
 * Runs daily via cron. For each eligible user (paid + Threads connected + autoPostEnabled),
 * generates posts and adds them to the scheduled post queue.
 */

import cron from "node-cron";
import * as db from "./db";
import { getPlan } from "../shared/plans";
import { generateThreadsPrompt } from "../shared/threadsPrompts";
import { invokeLLM } from "./_core/llm";
import { nanoid } from "nanoid";

// Post types and purposes for rotation
const POST_TYPES = [
  'hook_tree', 'expertise', 'local', 'proof', 'empathy', 'story',
  'list', 'offer', 'enemy', 'qa', 'trend', 'aruaru'
] as const;

const PURPOSES = ['cv', 'awareness', 'authority', 'fan'] as const;

// Optimal posting times (JST hours)
const POSTING_HOURS = [9, 12, 18, 21];

const JSON_SCHEMA = {
  type: 'json_schema' as const,
  json_schema: {
    name: 'threads_post',
    strict: true,
    schema: {
      type: 'object',
      properties: {
        title: { type: 'string', description: '投稿タイトル' },
        mainPost: { type: 'string', description: 'メイン投稿' },
        treePosts: { type: 'array', items: { type: 'string' }, description: 'ツリー投稿配列' },
        cta: { type: 'string', description: 'CTA' },
        hashtags: { type: 'array', items: { type: 'string' }, description: 'ハッシュタグ配列' },
        goal: { type: 'string', description: '投稿の狙い' },
        improvement: { type: 'string', description: '次回改善案' },
        expectedEffect: { type: 'string', description: '投稿の期待効果' },
        timingCandidate: { type: 'string', description: '投稿設置タイミング候補' },
        weeklyImprovementPoint: { type: 'string', description: '週次改善ポイント' },
        hookType: { type: 'string', description: '使用した1行目の型' },
        cvGoal: { type: 'string', description: 'CVゴール' },
      },
      required: ['title', 'mainPost', 'treePosts', 'cta', 'hashtags', 'goal', 'improvement', 'expectedEffect', 'timingCandidate', 'weeklyImprovementPoint', 'hookType', 'cvGoal'],
      additionalProperties: false,
    },
  },
};

/**
 * Get the next posting time for today
 */
function getNextPostingTime(index: number): Date {
  const now = new Date();
  const hour = POSTING_HOURS[index % POSTING_HOURS.length];
  const postTime = new Date(now);
  postTime.setHours(hour, Math.floor(Math.random() * 30), 0, 0); // Add random minutes for natural feel

  // If the time has passed today, schedule for tomorrow
  if (postTime <= now) {
    postTime.setDate(postTime.getDate() + 1);
  }

  return postTime;
}

/**
 * Generate a single auto-post for a user
 */
async function generateAutoPost(
  userId: number,
  project: any,
  postTypeIndex: number,
  purposeIndex: number,
  threadsAccountId: number,
  postingTimeIndex: number,
): Promise<boolean> {
  const postType = POST_TYPES[postTypeIndex % POST_TYPES.length];
  const purpose = PURPOSES[purposeIndex % PURPOSES.length];

  try {
    // Generate prompt
    const prompt = generateThreadsPrompt({
      businessType: project.businessType,
      area: project.area,
      target: project.target,
      mainProblem: project.mainProblem,
      strength: project.strength,
      proof: project.proof || undefined,
      link: project.ctaLink || undefined,
      postType,
      treeCount: 3,
      usp: project.usp || undefined,
      n1Customer: project.n1Customer || undefined,
      purpose,
    });

    // Call LLM
    const response = await invokeLLM({
      messages: [{ role: 'user', content: prompt }],
      response_format: JSON_SCHEMA,
    });

    const content = response.choices[0]?.message?.content;
    if (!content || typeof content !== 'string') {
      console.error(`[AutoPost] Empty LLM response for user ${userId}`);
      return false;
    }

    const result = JSON.parse(content);

    // Combine main post + tree posts + CTA + hashtags into full post content
    const fullContent = [
      result.mainPost,
      ...(result.treePosts || []),
      result.cta || '',
      (result.hashtags || []).map((h: string) => h.startsWith('#') ? h : `#${h}`).join(' '),
    ].filter(Boolean).join('\n\n');

    // Schedule the post
    const scheduledAt = getNextPostingTime(postingTimeIndex);

    await db.createScheduledPost({
      userId,
      projectId: project.id,
      threadsAccountId,
      scheduledAt,
      postContent: fullContent,
    });

    // Increment AI generation usage
    await db.incrementAiGenerationUsage(userId);

    // Save to history
    await db.saveAiGenerationHistory({
      userId,
      projectId: project.id,
      postType,
      content: JSON.stringify(result),
      metadata: JSON.stringify({ autoGenerated: true, purpose }),
    });

    console.log(`[AutoPost] Generated ${postType} post for user ${userId}, scheduled at ${scheduledAt.toISOString()}`);
    return true;
  } catch (error) {
    console.error(`[AutoPost] Failed to generate post for user ${userId}:`, error);
    return false;
  }
}

/**
 * Get number of posts to generate based on frequency setting
 */
function getPostCount(frequency: string): number {
  switch (frequency) {
    case 'three_daily': return 3;
    case 'twice_daily': return 2;
    case 'daily':
    default: return 1;
  }
}

/**
 * Process all eligible users and generate auto-posts
 */
export async function processAutoPostGeneration(): Promise<{ processed: number; generated: number; failed: number }> {
  let processed = 0;
  let generated = 0;
  let failed = 0;

  try {
    // Get all users eligible for auto-posting
    const users = await db.getAutoPostEligibleUsers();

    if (!users || users.length === 0) {
      console.log('[AutoPost] No eligible users found');
      return { processed: 0, generated: 0, failed: 0 };
    }

    console.log(`[AutoPost] Processing ${users.length} eligible users`);

    for (const user of users) {
      processed++;

      try {
        // Get user's first project (primary project for auto-posting)
        const projects = await db.getUserProjects(user.id);
        if (!projects || projects.length === 0) continue;

        const project = projects[0]; // Use first/primary project
        if (!project.businessType || !project.area || !project.target || !project.mainProblem || !project.strength) {
          console.log(`[AutoPost] Skipping user ${user.id} - incomplete project`);
          continue;
        }

        // Get user's active Threads account
        const accounts = await db.getActiveThreadsAccounts(user.id);
        if (!accounts || accounts.length === 0) continue;

        const account = accounts[0];

        // Determine how many posts to generate
        const postCount = getPostCount(user.autoPostFrequency);

        // Generate posts with rotation
        let typeIdx = user.lastAutoPostTypeIndex;
        let purposeIdx = user.lastAutoPurposeIndex;

        for (let i = 0; i < postCount; i++) {
          const success = await generateAutoPost(
            user.id,
            project,
            typeIdx,
            purposeIdx,
            account.id,
            i,
          );

          if (success) {
            generated++;
            typeIdx = (typeIdx + 1) % POST_TYPES.length;
            purposeIdx = (purposeIdx + 1) % PURPOSES.length;
          } else {
            failed++;
          }

          // Small delay between generations to avoid API rate limits
          if (i < postCount - 1) {
            await new Promise(r => setTimeout(r, 2000));
          }
        }

        // Update rotation indices
        await db.updateUserAutoPostIndices(user.id, typeIdx, purposeIdx);

      } catch (error) {
        console.error(`[AutoPost] Error processing user ${user.id}:`, error);
        failed++;
      }
    }

    console.log(`[AutoPost] Complete: ${processed} processed, ${generated} generated, ${failed} failed`);
  } catch (error) {
    console.error('[AutoPost] Fatal error:', error);
  }

  return { processed, generated, failed };
}

/**
 * Start the auto-post scheduler
 * Runs daily at 6:00 AM JST
 */
export function startAutoPostScheduler() {
  console.log('[AutoPost Scheduler] Starting...');

  // Run daily at 6:00 AM (JST = UTC+9, so 21:00 UTC previous day)
  cron.schedule('0 6 * * *', async () => {
    console.log('[AutoPost Scheduler] Running daily auto-post generation...');
    try {
      const result = await processAutoPostGeneration();
      console.log(`[AutoPost Scheduler] Complete: ${result.generated} generated, ${result.failed} failed out of ${result.processed} users`);
    } catch (error) {
      console.error('[AutoPost Scheduler] Fatal error in daily generation:', error);
    }
  }, {
    timezone: 'Asia/Tokyo',
  });

  console.log('[AutoPost Scheduler] Scheduled for 6:00 AM JST daily');
}
