/**
 * Default AI Generation Presets
 * These presets provide quick-start templates for common business types and purposes
 */

export interface PresetData {
  category: 'industry' | 'purpose' | 'post_type';
  name: string;
  description: string;
  icon: string;
  postType: string;
  defaultParams: {
    businessType?: string;
    area?: string;
    targetAudience?: string;
    mainProblem?: string;
    strength?: string;
    proof?: string;
    tone?: string;
    keywords?: string[];
  };
  displayOrder: number;
}

export const DEFAULT_PRESETS: PresetData[] = [
  // Industry-based presets
  {
    category: 'industry',
    name: '整体院・接骨院',
    description: '腰痛・肩こりなどの症状改善を訴求する投稿テンプレート',
    icon: 'Activity',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '整体院',
      area: '（お住まいの地域を入力）',
      targetAudience: '腰痛・肩こりに悩む30-50代',
      mainProblem: '慢性的な腰痛、肩こり、姿勢の悪さ、デスクワークによる体の不調',
      strength: '国家資格保持者による施術、根本原因にアプローチする独自メソッド',
      proof: '月間100名以上の施術実績、お客様満足度95%以上',
      tone: '親しみやすく、専門性を感じさせる',
      keywords: ['腰痛', '肩こり', '姿勢改善', '根本改善'],
    },
    displayOrder: 1,
  },
  {
    category: 'industry',
    name: '美容サロン・エステ',
    description: '美容効果や施術の特徴を魅力的に伝える投稿テンプレート',
    icon: 'Sparkles',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '美容サロン',
      area: '（お住まいの地域を入力）',
      targetAudience: '美容に関心の高い20-40代女性',
      mainProblem: 'シミ・シワ・たるみなどの肌悩み、セルフケアだけでは限界を感じている',
      strength: '最新美容機器導入、完全個室でリラックスできる空間、カウンセリング重視',
      proof: 'リピート率90%以上、施術実績3,000件以上',
      tone: '華やかで、高級感のある',
      keywords: ['美肌', '小顔', 'リフトアップ', 'エイジングケア'],
    },
    displayOrder: 2,
  },
  {
    category: 'industry',
    name: '飲食店・カフェ',
    description: 'メニューの魅力や店舗の雰囲気を伝える投稿テンプレート',
    icon: 'Coffee',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '飲食店',
      area: '（お住まいの地域を入力）',
      targetAudience: '地域住民・グルメ好きな20-40代',
      mainProblem: '美味しいお店を探している、特別な日のディナー先を探している',
      strength: 'こだわりの食材を使用、季節ごとのメニュー開発、居心地の良い空間',
      proof: '食べログ評価3.5以上、地元メディア掲載実績あり',
      tone: '親しみやすく、食欲をそそる',
      keywords: ['新メニュー', '季節限定', 'こだわり食材', '手作り'],
    },
    displayOrder: 3,
  },
  {
    category: 'industry',
    name: '小売店・雑貨店',
    description: '商品の特徴や使い方を紹介する投稿テンプレート',
    icon: 'ShoppingBag',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '小売店',
      area: '（お住まいの地域を入力）',
      targetAudience: 'ライフスタイルにこだわる20-40代',
      mainProblem: 'おしゃれで実用的な商品を探している、ギフト選びに悩んでいる',
      strength: 'バイヤーが厳選した商品ラインナップ、他では手に入らない限定品',
      proof: 'SNSフォロワー数増加中、リピーター率80%',
      tone: 'おしゃれで、ライフスタイル提案型',
      keywords: ['新商品', '限定品', 'おすすめ', 'ギフト'],
    },
    displayOrder: 4,
  },
  {
    category: 'industry',
    name: '士業・コンサルタント',
    description: '専門知識や実績をアピールする投稿テンプレート',
    icon: 'Briefcase',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '士業',
      area: '（お住まいの地域を入力）',
      targetAudience: '経営者・個人事業主',
      mainProblem: '経営上の課題解決、法的トラブルの不安、税務・会計の悩み',
      strength: '豊富な実務経験、わかりやすい説明、迅速な対応',
      proof: '相談実績500件以上、顧客満足度98%',
      tone: '信頼感があり、専門的',
      keywords: ['解決事例', '専門知識', 'サポート', '実績'],
    },
    displayOrder: 5,
  },
  {
    category: 'industry',
    name: 'フィットネス・ヨガ',
    description: '健康効果やプログラムの魅力を伝える投稿テンプレート',
    icon: 'Dumbbell',
    postType: 'hook_tree',
    defaultParams: {
      businessType: 'フィットネスジム',
      area: '（お住まいの地域を入力）',
      targetAudience: '健康・ダイエットに関心の高い20-50代',
      mainProblem: '運動不足、体型の悩み、健康への不安、一人では続かない',
      strength: '少人数制で丁寧な指導、初心者歓迎、個別プログラム作成',
      proof: '会員継続率85%、ダイエット成功者多数',
      tone: 'モチベーションを高める、前向き',
      keywords: ['ダイエット', '健康', 'ボディメイク', '体験レッスン'],
    },
    displayOrder: 6,
  },

  {
    category: 'industry',
    name: '不動産・住宅',
    description: '物件の魅力や住環境を伝える投稿テンプレート',
    icon: 'Home',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '不動産会社',
      area: '（お住まいの地域を入力）',
      targetAudience: '住宅購入・賃貸を検討中の20-40代ファミリー層',
      mainProblem: '理想の住まいが見つからない、物件選びの基準がわからない、住宅ローンの不安',
      strength: '地域密着で豊富な物件情報、住宅ローン相談対応、内覧同行サポート',
      proof: '年間成約100件以上、お客様満足度96%',
      tone: '信頼感があり、暮らしのイメージが湧く',
      keywords: ['新築', '中古物件', '住宅ローン', '内覧'],
    },
    displayOrder: 7,
  },
  {
    category: 'industry',
    name: '学習塾・スクール',
    description: '学習効果や指導方針を伝える投稿テンプレート',
    icon: 'GraduationCap',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '学習塾',
      area: '（お住まいの地域を入力）',
      targetAudience: '小中高生の保護者、受験を控えた学生',
      mainProblem: '成績が伸び悩んでいる、勉強のやり方がわからない、受験対策に不安がある',
      strength: '個別指導で一人ひとりに合わせたカリキュラム、経験豊富な講師陣',
      proof: '志望校合格率90%以上、成績アップ実績多数',
      tone: '安心感があり、成長を応援する',
      keywords: ['成績アップ', '受験対策', '個別指導', '無料体験'],
    },
    displayOrder: 8,
  },
  {
    category: 'industry',
    name: 'クリニック・歯科',
    description: '診療内容や院の特徴を伝える投稿テンプレート',
    icon: 'Stethoscope',
    postType: 'expertise',
    defaultParams: {
      businessType: 'クリニック',
      area: '（お住まいの地域を入力）',
      targetAudience: '健康に不安を抱える30-60代、予防医療に関心のある方',
      mainProblem: '体の不調が続いている、どの病院に行けばいいかわからない、待ち時間が長い',
      strength: '最新の医療機器導入、丁寧な問診と説明、予約制で待ち時間短縮',
      proof: '開院以来の診療実績、専門医資格保有',
      tone: '安心感があり、わかりやすい医療情報',
      keywords: ['健康', '予防', '検診', '専門治療'],
    },
    displayOrder: 9,
  },
  {
    category: 'industry',
    name: 'ペットサロン・動物病院',
    description: 'ペットケアの魅力やサービスを伝える投稿テンプレート',
    icon: 'Heart',
    postType: 'hook_tree',
    defaultParams: {
      businessType: 'ペットサロン',
      area: '（お住まいの地域を入力）',
      targetAudience: 'ペットを飼っている20-50代、ペットの健康に関心の高い飼い主',
      mainProblem: 'ペットのトリミング先選びに悩んでいる、ペットの健康管理が不安',
      strength: '動物看護師資格保有スタッフ、ストレスフリーな施術、送迎サービスあり',
      proof: 'トリミング実績月間200頭以上、口コミ評価4.8',
      tone: '温かみのある、ペット愛にあふれた',
      keywords: ['トリミング', 'ペットケア', '健康チェック', 'かわいい'],
    },
    displayOrder: 10,
  },
  {
    category: 'industry',
    name: '美容室・ヘアサロン',
    description: 'ヘアスタイルや技術力を魅力的に伝える投稿テンプレート',
    icon: 'Scissors',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '美容室',
      area: '（お住まいの地域を入力）',
      targetAudience: 'おしゃれに敏感な20-40代男女',
      mainProblem: '自分に似合う髪型がわからない、カラーの持ちが悪い、髪のダメージが気になる',
      strength: 'トレンドを取り入れた提案力、ダメージレスな施術、マンツーマン対応',
      proof: 'ホットペッパー口コミ4.7以上、リピート率85%',
      tone: 'トレンド感があり、おしゃれ',
      keywords: ['ヘアスタイル', 'カラー', 'トリートメント', '似合わせ'],
    },
    displayOrder: 11,
  },
  {
    category: 'industry',
    name: 'ネイルサロン',
    description: 'ネイルデザインやサロンの魅力を伝える投稿テンプレート',
    icon: 'Palette',
    postType: 'hook_tree',
    defaultParams: {
      businessType: 'ネイルサロン',
      area: '（お住まいの地域を入力）',
      targetAudience: 'ネイルにこだわる20-40代女性',
      mainProblem: '爪が弱くてネイルが楽しめない、デザインのマンネリ化、持ちが悪い',
      strength: 'パラジェル取扱い、豊富なデザインサンプル、丁寧なケア',
      proof: 'Instagram掲載デザイン500種以上、リピート率90%',
      tone: '華やかで、トレンド感のある',
      keywords: ['ジェルネイル', 'デザイン', 'ケア', '季節ネイル'],
    },
    displayOrder: 12,
  },
  {
    category: 'industry',
    name: '写真スタジオ',
    description: '撮影プランや作品の魅力を伝える投稿テンプレート',
    icon: 'Camera',
    postType: 'story',
    defaultParams: {
      businessType: '写真スタジオ',
      area: '（お住まいの地域を入力）',
      targetAudience: '記念撮影を検討中のファミリー、カップル、マタニティの方',
      mainProblem: '大切な瞬間を綺麗に残したい、スタジオ選びに迷っている、自然な表情を撮りたい',
      strength: '自然光スタジオ、衣装レンタル無料、データ全カット納品',
      proof: '撮影実績年間500組以上、Googleレビュー4.9',
      tone: '温かみのある、感動を伝える',
      keywords: ['記念撮影', '家族写真', 'ウェディング', 'マタニティ'],
    },
    displayOrder: 13,
  },
  {
    category: 'industry',
    name: '花屋・フラワーショップ',
    description: '花の魅力やアレンジメントを伝える投稿テンプレート',
    icon: 'Flower2',
    postType: 'hook_tree',
    defaultParams: {
      businessType: '花屋',
      area: '（お住まいの地域を入力）',
      targetAudience: '花やグリーンが好きな20-50代、ギフトを探している方',
      mainProblem: '花の選び方がわからない、長持ちさせる方法を知りたい、特別なギフトを探している',
      strength: '毎朝市場で仕入れる新鮮な花、オーダーメイドアレンジ、配達対応',
      proof: 'ウェディング装花実績100件以上、Google口コミ4.8',
      tone: '華やかで、季節感のある',
      keywords: ['花束', 'アレンジメント', 'ギフト', '季節の花'],
    },
    displayOrder: 14,
  },

  // Purpose-based presets
  {
    category: 'purpose',
    name: '新規顧客獲得',
    description: '初めてのお客様に向けた魅力的な投稿テンプレート',
    icon: 'UserPlus',
    postType: 'hook_tree',
    defaultParams: {
      targetAudience: '新規顧客',
      mainProblem: 'サービスの存在を知らない、初めての利用に不安がある',
      strength: '初回限定特典あり、丁寧なカウンセリング、お試し体験可能',
      tone: '親しみやすく、わかりやすい',
       keywords: ['初回限定', '体験', 'お試し', '特典'],
    },
    displayOrder: 15,
  },
  {
    category: 'purpose',
    name: 'リピーター促進',
    description: '既存顧客の再来店を促す投稿テンプレート',
    icon: 'RefreshCw',
    postType: 'hook_tree',
    defaultParams: {
      targetAudience: '既存顧客',
      mainProblem: '継続の動機づけが弱い、次回予約のきっかけがない',
      strength: 'リピーター限定特典、ポイント制度、会員限定イベント',
      tone: '感謝の気持ちを込めた、親密',
      keywords: ['リピーター特典', 'ポイント', '会員限定', '感謝'],
    },
    displayOrder: 16,
  },
  {
    category: 'purpose',
    name: 'イベント告知',
    description: 'イベントやキャンペーンを告知する投稿テンプレート',
    icon: 'Calendar',
    postType: 'hook_tree',
    defaultParams: {
      targetAudience: '地域住民・フォロワー',
      mainProblem: 'イベント情報が届いていない、参加のきっかけがない',
      strength: '限定企画、先着特典、参加者特典あり',
      tone: 'ワクワク感のある、期待を高める',
      keywords: ['イベント', 'キャンペーン', '期間限定', '先着'],
    },
    displayOrder: 17,
  },
  {
    category: 'purpose',
    name: '商品・サービス紹介',
    description: '新商品や新サービスを紹介する投稿テンプレート',
    icon: 'Package',
    postType: 'hook_tree',
    defaultParams: {
      targetAudience: '潜在顧客',
      mainProblem: '商品・サービスの魅力が伝わっていない、比較検討中',
      strength: '他社にない独自の特徴、高いコストパフォーマンス',
      tone: '魅力的で、ベネフィットを強調',
      keywords: ['新登場', 'おすすめ', '特徴', 'こだわり'],
    },
    displayOrder: 18,
  },
  {
    category: 'purpose',
    name: 'お客様の声・実績紹介',
    description: 'お客様の声や実績を紹介して信頼を築く投稿テンプレート',
    icon: 'MessageCircle',
    postType: 'proof',
    defaultParams: {
      targetAudience: '潜在顧客',
      mainProblem: 'サービスの効果に不安がある、口コミや実績を知りたい',
      strength: '豊富な実績、お客様からの高評価',
      proof: 'お客様の声多数、ビフォーアフター事例あり',
      tone: '信頼感があり、共感を呼ぶ',
      keywords: ['お客様の声', '実績', 'ビフォーアフター', '喜びの声'],
    },
    displayOrder: 19,
  },

  // Post type-based presets
  {
    category: 'post_type',
    name: 'フック型ツリー投稿',
    description: '注目を集めるフックから始まる連続投稿テンプレート',
    icon: 'TrendingUp',
    postType: 'hook_tree',
    defaultParams: {
      tone: 'インパクトのある、続きが気になる',
      keywords: ['驚き', '意外', '知らなかった', '実は'],
    },
    displayOrder: 20,
  },
  {
    category: 'post_type',
    name: 'ストーリー型投稿',
    description: 'ストーリーで共感を呼ぶ投稿テンプレート',
    icon: 'BookOpen',
    postType: 'story',
    defaultParams: {
      tone: '共感を呼ぶ、ストーリー性のある',
      keywords: ['体験談', 'エピソード', '変化', '成長'],
    },
    displayOrder: 21,
  },
  {
    category: 'post_type',
    name: 'リスト型投稿',
    description: '箇条書きでわかりやすく伝える投稿テンプレート',
    icon: 'List',
    postType: 'list',
    defaultParams: {
      tone: 'わかりやすく、実用的',
      keywords: ['〇選', 'まとめ', 'ポイント', 'コツ'],
    },
    displayOrder: 22,
  },
];
