import { Template } from "./types";

export const TEMPLATES: Template[] = [
  {
    id: "empathy-problem-solution-cta",
    name: "共感→問題提起→解決策→行動喚起",
    description: "読者の共感を得て、問題を提起し、解決策を提示して行動を促す王道パターン",
    icon: "💡",
    requiredFields: [
      { key: "storeName", label: "店舗名", placeholder: "例：〇〇整体院", required: true },
      { key: "target", label: "対象", placeholder: "例：30代女性、デスクワーカー", required: true },
      { key: "problem", label: "悩み・課題", placeholder: "例：慢性的な肩こり、頭痛", required: true, multiline: true },
      { key: "benefit", label: "ベネフィット", placeholder: "例：根本から整える、日常が楽になる", required: true, multiline: true },
      { key: "cta", label: "行動喚起", placeholder: "例：初回限定キャンペーン実施中", required: true },
      { key: "notes", label: "注意書き", placeholder: "例：効果には個人差があります", required: false, multiline: true },
    ],
    outputRules: [
      { role: "hook", contentTemplate: "{{target}}の方、こんなお悩みありませんか?" },
      { role: "empathy", contentTemplate: "{{problem}}で毎日がつらい…そんな声をよく聞きます。" },
      { role: "problem", contentTemplate: "実はその原因、〇〇にあるかもしれません。" },
      { role: "solution", contentTemplate: "{{storeName}}では、{{benefit}}アプローチで根本からサポートします。" },
      { role: "cta", contentTemplate: "{{cta}}\\n\\n{{notes}}" },
    ],
  },
  {
    id: "faq",
    name: "FAQ型",
    description: "よくある質問に答える形式で、読者の疑問を解消しながら信頼を構築",
    icon: "❓",
    requiredFields: [
      { key: "storeName", label: "店舗名", placeholder: "例：〇〇美容サロン", required: true },
      { key: "target", label: "対象", placeholder: "例：美容に関心がある方", required: true },
      { key: "problem", label: "よくある質問", placeholder: "例：痛みはありますか？効果はどのくらい？", required: true, multiline: true },
      { key: "benefit", label: "回答・ベネフィット", placeholder: "例：痛みはほぼなく、個人差はありますが多くの方が実感", required: true, multiline: true },
      { key: "cta", label: "行動喚起", placeholder: "例：無料カウンセリング実施中", required: true },
      { key: "notes", label: "注意書き", placeholder: "例：効果には個人差があります", required: false, multiline: true },
    ],
    outputRules: [
      { role: "hook", contentTemplate: "{{storeName}}によくいただく質問をまとめました！" },
      { role: "question1", contentTemplate: "Q1: {{problem}}" },
      { role: "answer1", contentTemplate: "A1: {{benefit}}" },
      { role: "question2", contentTemplate: "Q2: どんな方におすすめですか？" },
      { role: "answer2", contentTemplate: "A2: {{target}}の方に特におすすめです。" },
      { role: "cta", contentTemplate: "{{cta}}\\n\\n{{notes}}" },
    ],
  },
  {
    id: "testimonial",
    name: "体験談型",
    description: "実際のお客様の声や事例を通じて、リアルな効果と信頼性を伝える",
    icon: "⭐",
    requiredFields: [
      { key: "storeName", label: "店舗名", placeholder: "例：〇〇鍼灸院", required: true },
      { key: "target", label: "お客様属性", placeholder: "例：40代男性、会社員", required: true },
      { key: "problem", label: "来店前の悩み", placeholder: "例：腰痛で仕事に集中できない", required: true, multiline: true },
      { key: "benefit", label: "施術後の変化", placeholder: "例：痛みが和らぎ、仕事に集中できるように", required: true, multiline: true },
      { key: "cta", label: "行動喚起", placeholder: "例：あなたも体験してみませんか？", required: true },
      { key: "notes", label: "注意書き", placeholder: "例：効果には個人差があります", required: false, multiline: true },
    ],
    outputRules: [
      { role: "hook", contentTemplate: "お客様の声をご紹介します✨" },
      { role: "profile", contentTemplate: "{{target}}のお客様" },
      { role: "before", contentTemplate: "【来店前】\\n{{problem}}" },
      { role: "after", contentTemplate: "【施術後】\\n{{benefit}}" },
      { role: "voice", contentTemplate: "「{{storeName}}に通って本当に良かった」とのお声をいただきました。" },
      { role: "cta", contentTemplate: "{{cta}}\\n\\n{{notes}}" },
    ],
  },
  {
    id: "checklist",
    name: "チェックリスト型",
    description: "読者が自己診断できるチェックリスト形式で、関心を引き出す",
    icon: "✅",
    requiredFields: [
      { key: "storeName", label: "店舗名", placeholder: "例：〇〇整体院", required: true },
      { key: "target", label: "対象", placeholder: "例：肩こり・腰痛でお悩みの方", required: true },
      { key: "problem", label: "チェック項目", placeholder: "例：朝起きると体が痛い、長時間座ると辛い", required: true, multiline: true },
      { key: "benefit", label: "解決策・ベネフィット", placeholder: "例：姿勢を整えることで根本改善をサポート", required: true, multiline: true },
      { key: "cta", label: "行動喚起", placeholder: "例：初回体験キャンペーン実施中", required: true },
      { key: "notes", label: "注意書き", placeholder: "例：効果には個人差があります", required: false, multiline: true },
    ],
    outputRules: [
      { role: "hook", contentTemplate: "こんな症状、当てはまりませんか？" },
      { role: "checklist", contentTemplate: "☑️ {{problem}}\\n\\n3つ以上当てはまる方は要注意です。" },
      { role: "reason", contentTemplate: "これらの症状、実は体のバランスが崩れているサインかもしれません。" },
      { role: "solution", contentTemplate: "{{storeName}}では、{{benefit}}" },
      { role: "target", contentTemplate: "{{target}}の方、ぜひ一度ご相談ください。" },
      { role: "cta", contentTemplate: "{{cta}}\\n\\n{{notes}}" },
    ],
  },
];
